---
- name: Install Elasticsearch
  hosts: elasticsearch
  roles: 
    - elastic
- name: Install Kibana
  hosts: kbn
  roles:
    - role: kibana-role
- name: Install Filebeat
  hosts: flbt
  roles:
    - filebeat-role
