---
filebeat_version: "7.14.0"
filebeat_install_type: remote
elastic_ip: hostvars['elastic']['ansible_facts']['default_ipv4']['address']
kibana_ip: hostvars['kbn']['ansible_facts']['default_ipv4']['address']
