---
- name: Install Elasticsearch
  hosts: elasticsearch
  handlers:
    - name: restart Elasticsearch
      become: true
      service:
        name: elasticsearch
        state: restarted
  tasks:
    - name: "Download Elasticsearch's deb"
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_stack_version }}-amd64.deb"
        dest: "/tmp/elasticsearch-{{ elk_stack_version }}-amd64.deb"
      register: download_elastic
      until: download_elastic is succeeded
    - name: Install Elasticsearch
      become: true
      apt:
        deb: "/tmp/elasticsearch-{{ elk_stack_version }}-amd64.deb"
        state: present
    - name: Configure Elasticsearch
      become: true
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        mode: '0755'
      notify: restart Elasticsearch
- name: Install Kibana
  hosts: kbn
  handlers:
    - name: restart Kibana
      service:
        name: kibana
        state: restarted
  tasks:
    - name: "Download Kibana's deb"
      get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_stack_version }}-amd64.deb"
        dest: "/tmp/kibana-{{ elk_stack_version }}-amd64.deb"
      register: download_kibana
      until: download_kibana is succeeded
    - name: Install Kibana
      apt:
        deb: "/tmp/kibana-{{ elk_stack_version }}-amd64.deb"
        state: present
    - name: Configure Kibana
      template:
        src: kibana.yml.j2
        dest: /etc/kibana/kibana.yml
        mode: '0755'
      notify: restart Kibana
- name: Install Filebeat
  hosts: flbt
  handlers:
    - name: restart Filebeat
      become: true
      service:
        name: filebeat
        state: restarted
  tasks:
    - name: "Download Filebeat's rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
        dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
      register: download_filebeat
      until: download_filebeat is succeeded
    - name: Install Filebeat
      become: true
      yum:
        name: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
        state: present
    - name: Configure Filebeat
      become: true
      template:
        src: filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
        mode: '0755'
      notify: restart Filebeat
    - name: Enable the system module
      become: true
      command:
        cmd: filebeat modules enable system
      register: filebeat_module
      changed_when: filebeat_module.stdout != 'Module system is already enabled'
    - name: Loads the Kibana dashboards
      become: true
      command:
        cmd: filebeat setup
      register: filebeat_setup
      changed_when: false
      until: filebeat_setup is succeeded
