---
- name: "Download Kibana's rpm"
  copy:
    src: "/dist/kibana-{{ kibana_version }}-x86_64.rpm"
    mode: 0644
    dest: "files/kibana-{{ kibana_version }}-x86_64.rpm"
  delegate_to: localhost
  when: kibana_install_type == 'remote'
- name: Copy Kibana to manage host
  copy:
    src: "files/kibana-{{ kibana_version }}-x86_64.rpm"
    mode: 0644
    dest: "/tmp/kibana-{{ kibana_version }}-x86_64.rpm"

