---
- name: "Download Kibana's deb"
  copy:
    src: "/dist/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0644
    dest: "files/kibana-{{ kibana_version }}-amd64.deb"
  delegate_to: localhost
  when: kibana_install_type == 'remote'
- name: Copy Kibana to manage host
  copy:
    src: "files/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0644
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"

